<?php
    require_once('auth.php');
    require_once('user.php');
    require_once('post.php');
    require_once('postCommentReaction.php');
    require_once('postCategory.php');
    require_once('contact.php');
    require_once('newsletter.php');
    require_once('postComment.php')
?>
